name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }


jobs:
  validate-renovate-config:
    name: Validate Renovate configuration
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
      - name: Get dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
